config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :events do
    member do
      post 'update_attendance'
    end
  end
  resources :users do
    collection do
      post 'login'
    end
  end

  resources :attendances

end

app/models/attendance.rb
# == Schema Information
#
# Table name: attendances
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  event_id     :integer
#  has_attended :boolean
#  user_type    :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Attendance < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  date        :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Event < ActiveRecord::Base

  # associations
  has_many :attendances
  has_many :users, through: :attendances

  # validations
  validates :title, presence: true, length: { in: 2..255 }
  validates_datetime :date

  def admin_users
    users.where('attendances.user_type' => 'ADMIN')
  end

  def student_attendances
    attendances.where(user_type: 'STUDENT')
  end

  def attendance_rate
    total_attendance = student_attendances.count
    actual_attendance = student_attendances.where(has_attended: true).count
    "#{actual_attendance} out of #{total_attendance}"
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  password   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
    
    
  # associations
  has_many :attendances
  has_many :events, through: :attendances
    
  # validations
  validates :name, presence: true, length: { in: 2..255 }
  validates :email, presence: true, email: true, uniqueness: true, length: { maximum: 255 }
  validates :password, presence: true, length: { in: 6..40 }

  def attended_events
    events.where('attendances.has_attended': true)    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attendances_controller.rb
# == Schema Information
#
# Table name: attendances
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  event_id     :integer
#  has_attended :boolean
#  user_type    :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  def create
    @attendance = Attendance.new(attendance_params)

    if @attendance.save
      redirect_to @attendance, notice: 'Attendance was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /attendances/1
  def update
    if @attendance.update(attendance_params)
      redirect_to @attendance, notice: 'Attendance was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /attendances/1
  def destroy
    @attendance.destroy
    redirect_to attendances_url, notice: 'Attendance was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def attendance_params
      params.require(:attendance).permit(:user_id, :event_id, :has_attended, :user_type)
    end
end

app/controllers/concerns/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update]
  def index
    @attendances = Attendance.all
  end

  def show
  end

  def update
    if @attendance.update(attendance_params)
      redirect_to @attendance, notice: 'Attendance was successfully updated.'
    else
      render :edit
    end
  end

  def edit
  end

  private

  def set_attendance
    @attendance = Attendance.find(params[:id])
  end

  def attendance_params
    params.require(:attendance).permit(:has_attended)
  end
end

app/controllers/events_controller.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  date        :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :update_attendance]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end  
  
  def update_attendance
    attended_hash = params[:attendance]
    @event.attendances.each do |attendance|
      has_attended = attended_hash.key?(attendance.id.to_s)
      if has_attended != attendance.has_attended
        if has_attended
          attendance.update(has_attended: true)
        else
          attendance.update(has_attended: false)
        end
      end
    end
    redirect_to @event, notice: 'Event was successfully updated.'
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:title, :description, :date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  password   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/attendances/_form.html.erb
<%= simple_form_for @attendance,
    url: attendance_path(@attendance),
    method: :put do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :has_attended, as: :select, include_blank: false %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendance Listing</h1>

<% @attendances.each do |attendance| %>
  <div class="card">
      <div class="card-block">
        <h4 class="card-title"><%= attendance.event.title %></h4>
        <p class="card-text"><%= attendance.user.name %></p>
        <p><%= link_to 'Show Attendance', attendance_path(attendance), class: 'text-right' %></p>
        <div class="card-footer text-muted">
          <%= attendance.event.date %>
        </div>
      </div>
  </div>
<% end %>

app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
    <p>
      <strong>Attendance Event:</strong>
      <%= @attendance.event.title %>
    </p>

    <p>
      <strong>User:</strong>
      <%= @attendance.user.name %>
    </p>

    <p>
      <strong>Attended Event:</strong>
      <%= @attendance.has_attended ? 'Yes' : 'No' %>
    </p>

    <div class="pull-xs-right">
        <%= link_to 'Edit', edit_attendance_path(@attendance), class: 'btn btn-primary' %>
    </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events Listing</h1>

<p><%= link_to 'New Event', new_event_path, class: 'btn btn-secondary' %></p>

<div class="card-columns">
  <% @events.each do |event| %>
    <div class="card">
        <div class="card-block">
          <h4 class="card-title">
            <%= event.title %>
          </h4>
          <p class="pull-xs-right"><%= event.attendance_rate %></p>
          <p class="card-text"><%= event.description %></p>
          <p><%= link_to 'Show Event', event_path(event), class: 'text-right' %></p>
          <div class="card-footer text-muted">
            <%= event.date %>
          </div>
        </div>
    </div>
    <% end %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
    <p>
      <strong>Title:</strong>
      <%= @event.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <div class="pull-xs-right">
        <%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %>
    </div>
</div>


<h3>Admin</h3>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event.admin_users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h3>Attendance</h3>

<%= form_tag("/events/#{@event.id}/update_attendance") do |f| %>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Attended</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @event.student_attendances.each do |attendance| %>
          <tr>
            <td><%= attendance.user.name %></td>
            <td><%= attendance.user.email %></td>
            <td><%= check_box_tag("attendance[#{attendance.id}]", "true", attendance.has_attended) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="actions pull-xs-right">
        <%= submit_tag("Update attendance", class: 'btn btn-primary') %>
    </div>
<% end %>

app/views/home/index.html.erb
<br>
<h3>About us</h3>
<br>
<h3>Vision</h3>
<br>
<h3>Mission</h3>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-primary">

  <%= link_to 'Coding Girls', events_path, class: "navbar-brand" %>

    <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Events', events_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Attendances', attendances_path, class: 'nav-link' %></li>
    </ul>
    <ul class="nav navbar-nav pull-right pull-xs-right">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            User
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="Preview">
            <a class="dropdown-item" href="#">User profile</a>
        </div>
        </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Girls</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">
    <%= yield %>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>